In [2]:
ls

README.md               crsp_monthly_named.txt  eap2.tex
crsp_daily_named.txt    eap.tex                 eap3.pdf
crsp_data.ipynb         eap2.pdf                eap3.tex

In [3]:
import pandas as pd

In [9]:
df = pd.read_csv('crsp_monthly_named.txt', sep='\t')
dd = pd.read_csv('crsp_daily_named.txt', sep='\t')

/var/folders/r3/t04qzh290tl91rj4_h2w1tlh0000gn/T/ipykernel_10772/356178326.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  dd = pd.read_csv('crsp_daily_named.txt', sep='\t')

| Column         | Description                                                        |
|----------------|--------------------------------------------------------------------|
| `permno`       | Permanent security identifier assigned by CRSP                    |
| `date`         | Date of the return (typically end of the month)                   |
| `ret`          | Monthly return (including dividends)                              |
| `shrout`       | Shares outstanding (in thousands)                                 |
| `prc`          | Closing price (signed to indicate positive/negative return days)  |
| `primaryexch`  | Primary exchange where the stock is traded                        |
| `siccd`        | Standard Industrial Classification (SIC) code                     |
| `mktcap`       | Market capitalization (price Ã— shares outstanding)                |
| `mktcap_lag`   | Lagged market capitalization (from previous month)                |
| `exchange`     | Exchange code or name                                             |
| `industry`     | Industry classification                                           |
| `ret_excess`   | Excess return over risk-free rate                                 |
| `gvkey`        | Compustat company identifier                                      |
| `securitynm`   | Security name                                                     |
| `securitytype` | Type of security (e.g., common stock)                             |
| `ticker`       | Ticker symbol                                                     |
| `tradingsymbol`| Trading symbol, often exchange-specific                           |

In [33]:

#df_subset = df[['date', 'permno', 'ret', 'ret_excess']]

df_subset = dd[['date', 'permno', 'ret', 'ret_excess']]

# Aggregate using pivot_table to handle duplicates
ret_wide = df_subset.pivot_table(index='date', columns='permno', values='ret', aggfunc='mean')
ret_excess_wide = df_subset.pivot_table(index='date', columns='permno', values='ret_excess', aggfunc='mean')

# Rename columns
ret_wide.columns = [f'ret_{int(col)}' for col in ret_wide.columns]
ret_excess_wide.columns = [f'ret_excess_{int(col)}' for col in ret_excess_wide.columns]

# Combine into single DataFrame
final_df = pd.concat([ret_wide, ret_excess_wide], axis=1)

# Optional: sort by date
final_df = final_df.sort_index()

In [34]:
final_df

,ret_10000,ret_10001,ret_10002,ret_10003,ret_10004,ret_10005,ret_10006,ret_10007,ret_10008,ret_10009,...,ret_excess_93423,ret_excess_93426,ret_excess_93428,ret_excess_93429,ret_excess_93430,ret_excess_93432,ret_excess_93433,ret_excess_93434,ret_excess_93435,ret_excess_93436
date,,,,,,,,,,,,,,,,,,,,,
1926-01-02,NaN,NaN,NaN,NaN,NaN,NaN,0.001147,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-01-04,NaN,NaN,NaN,NaN,NaN,NaN,0.017182,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-01-05,NaN,NaN,NaN,NaN,NaN,NaN,-0.004505,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-01-06,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-01-07,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.002698,0.007067,NaN,NaN,NaN,NaN,NaN,0.034336,NaN,-0.007911
2023-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.006024,0.006714,NaN,NaN,NaN,NaN,NaN,0.029316,NaN,0.015906
2023-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.000210,0.000089,NaN,NaN,NaN,NaN,NaN,0.026079,NaN,0.018612
2023-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.031595,0.004572,NaN,NaN,NaN,NaN,NaN,-0.002206,NaN,-0.031804
2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.003793,0.013175,NaN,NaN,NaN,NaN,NaN,0.166457,NaN,-0.018774

In [37]:
id_vars = ['permno', 'securitynm', 'securitytype', 'ticker', 'tradingsymbol']
unique_info = dd[id_vars].drop_duplicates(subset='permno').set_index('permno')

unique_info_dropna = dd.dropna(subset=['securitytype', 'ticker', 'tradingsymbol'])[id_vars].drop_duplicates(subset='permno').set_index('permno')

In [40]:
#final_df.to_csv("daily_crsp_restored.csv",index=False)
unique_info.to_csv("permo_pivot_daily.csv")

#final_df.to_csv("monthly_crsp_restored.csv",index=False)
#unique_info.to_csv("permo_pivot_monthly.csv")